name: Release

# Declare default permissions as read only.
permissions: read-all

on:
  push:
    branches: [main]

jobs:
  detect:
    name: Detect New Changelog Version
    permissions:
      contents: write
    uses: outoforbitdev/reusable-workflows-library/.github/workflows/detect-new-changelog-version.yml@6d3deb76a8bc67b0c56bfae3e58d9b9566a967d0 # v1.3.0
  publish:
    name: Publish Release
    needs: detect
    if: needs.detect.outputs.should-release == 'true'
    permissions:
      contents: write
    uses: outoforbitdev/reusable-workflows-library/.github/workflows/publish-release.yml@6d3deb76a8bc67b0c56bfae3e58d9b9566a967d0 # v1.3.0
    with:
      version: ${{ needs.detect.outputs.new-version }}
      prerelease: ${{ needs.detect.outputs.is-prerelease == 'true' }}
      release-notes: ${{ needs.detect.outputs.release-notes }}
      draft: false
